spring.redis.cluster.nodes=127.0.0.1:7777
spring.redis.password=pass.123

spring.redis.hktv.cluster.nodes=127.0.0.1:7777
spring.redis.hktv.password=pass.123

spring.redis.lm.cluster.nodes=127.0.0.1:7778
spring.redis.lm.password=pass.123

spring.rabbitmq.default.addresses=${RABBITMQ_ADDRESSES:localhost:5972}
spring.rabbitmq.default.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.default.password=${RABBITMQ_PASSWORD:guest}

spring.datasource.url=jdbc:mysql://localhost:3416/inventory?serverZoneId=Asia/Hong_Kong
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

logging.level.root=INFO
